# Generated by Django 3.0.8 on 2020-08-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('link', models.CharField(max_length=1500)),
                ('news_from', models.CharField(max_length=500)),
                ('news_about_utopia', models.BooleanField(default=False)),
                ('news_by_utopia', models.BooleanField(default=False)),
            ],
        ),
    ]
